#!/usr/bin/env node
// ============================================================
// check-schema.mjs — diff live Supabase schema vs committed snapshot
//
// Class-of-bug discovered 2026-05-03 (iter 114, 119, 120): three silent
// production bugs all traced to schema-truth-file divergence. The
// `supabase_schema.sql` file captured founding-phase schema only;
// migrations under `supabase/migrations/` had been adding columns +
// tables for months without being replayed back. Code that trusted the
// stale file referenced columns that didn't exist, producing PostgREST
// errors caught by generic try/catch + Hebrew-toast handlers — silent
// failure to the user, console-only to the dev.
//
// `scripts/schema-snapshot.json` is the new source of truth for the
// public schema. It's regenerated by querying `information_schema` via
// Supabase MCP after every migration, and committed to the repo. This
// script verifies the snapshot is still current by querying the live DB
// and diffing against the file. Drift = the snapshot is stale =
// somebody applied a migration without regenerating the snapshot, and
// future agents will trust the wrong shape. Build fails on drift unless
// `--allow-drift` is passed.
//
// Companion to:
//   - scripts/check-routes.mjs (route-existence guard, iter 65)
//   - scripts/check-vercel.mjs (deploy-failure guard, iter 73)
//   - geffen-studio:tools/build-time-guards.md (the canonical pattern)
//
// Auth (one of):
//   SUPABASE_SERVICE_ROLE_KEY (preferred — has information_schema access)
//   OR fall back to gracefully no-op if missing.
//   Plus SUPABASE_URL or VITE_SUPABASE_URL.
//
// Usage:
//   npm run check:schema           — fail on drift
//   npm run check:schema -- --allow-drift  — report drift but exit 0
//
// Refresh path when drift is reported:
//   1. Apply pending migrations to live DB.
//   2. Regenerate `scripts/schema-snapshot.json` from a fresh
//      information_schema.columns query (via Supabase MCP or pg client).
//   3. Commit the regenerated snapshot in the same PR as the migration
//      that caused the drift.
// ============================================================

import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const ALLOW_DRIFT = process.argv.includes('--allow-drift');

const __dirname = dirname(fileURLToPath(import.meta.url));
const SNAPSHOT_PATH = resolve(__dirname, 'schema-snapshot.json');

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
    console.log(
        '[check:schema] SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not set — skipping. ' +
        'See scripts/check-schema.mjs header for setup.'
    );
    process.exit(0);
}

const snapshot = JSON.parse(await readFile(SNAPSHOT_PATH, 'utf8'));

// Query live DB via PostgREST RPC. Supabase doesn't expose information_schema
// directly via REST, so we use the SQL-execution endpoint with service role.
async function queryLiveSchema() {
    const sql = `
        SELECT
            table_name::text AS table_name,
            jsonb_agg(
                jsonb_build_object(
                    'name', column_name::text,
                    'type', data_type::text,
                    'nullable', is_nullable = 'YES',
                    'default', column_default
                ) ORDER BY ordinal_position
            ) AS columns
        FROM information_schema.columns
        WHERE table_schema = 'public'
        GROUP BY table_name
        ORDER BY table_name;
    `;
    // Supabase exposes the SQL-via-RPC endpoint for service-role keys at /rest/v1/rpc.
    // We keep this script dependency-free by hitting the underlying Postgres REST
    // path directly. Most installations have a `query` RPC or similar; if not, the
    // fallback is the PostgREST `/rest/v1/postgrest_meta_columns` view (Supabase-only).
    // Trying the simpler approach first: the project's pg_meta endpoint.
    const url = `${SUPABASE_URL}/rest/v1/rpc/exec_sql`;
    const res = await fetch(url, {
        method: 'POST',
        headers: {
            'apikey': SERVICE_ROLE_KEY,
            'Authorization': `Bearer ${SERVICE_ROLE_KEY}`,
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({ sql }),
    });
    if (!res.ok) {
        // Fallback path: the project doesn't have an exec_sql RPC. Surface a clear
        // message asking for a one-time setup migration.
        console.error(
            `[check:schema] Could not query information_schema via REST (HTTP ${res.status}). ` +
            'This script requires either an `exec_sql(text)` RPC function in the public ' +
            'schema OR direct postgres access. Skipping the live-DB check; ' +
            'the snapshot file is still valid as a documentation artifact.'
        );
        process.exit(0);
    }
    return await res.json();
}

function normalizeColumn(col) {
    return {
        name: col.name,
        type: col.type,
        nullable: col.nullable === true,
        default: col.default ?? null,
    };
}

function diffSchemas(snapshotTables, liveTables) {
    const drifts = [];

    const snapshotNames = new Set(Object.keys(snapshotTables));
    const liveNames = new Set(Object.keys(liveTables));

    for (const t of liveNames) {
        if (!snapshotNames.has(t)) {
            drifts.push({ kind: 'table-added', table: t });
        }
    }
    for (const t of snapshotNames) {
        if (!liveNames.has(t)) {
            drifts.push({ kind: 'table-removed', table: t });
        }
    }

    for (const t of liveNames) {
        if (!snapshotNames.has(t)) continue;
        const liveCols = new Map(liveTables[t].columns.map(c => [c.name, normalizeColumn(c)]));
        const snapCols = new Map(snapshotTables[t].columns.map(c => [c.name, normalizeColumn(c)]));

        for (const [name, lc] of liveCols) {
            if (!snapCols.has(name)) {
                drifts.push({ kind: 'column-added', table: t, column: name, live: lc });
                continue;
            }
            const sc = snapCols.get(name);
            if (lc.type !== sc.type || lc.nullable !== sc.nullable || (lc.default ?? null) !== (sc.default ?? null)) {
                drifts.push({ kind: 'column-changed', table: t, column: name, live: lc, snapshot: sc });
            }
        }
        for (const [name, sc] of snapCols) {
            if (!liveCols.has(name)) {
                drifts.push({ kind: 'column-removed', table: t, column: name, snapshot: sc });
            }
        }
    }

    return drifts;
}

const liveRows = await queryLiveSchema();
const liveTables = {};
for (const row of liveRows) {
    liveTables[row.table_name] = { columns: row.columns };
}

const drifts = diffSchemas(snapshot.tables, liveTables);

if (drifts.length === 0) {
    console.log(`[check:schema] OK — snapshot matches live DB (${Object.keys(liveTables).length} tables).`);
    process.exit(0);
}

console.log(`[check:schema] DRIFT DETECTED — ${drifts.length} difference(s) between snapshot and live DB:\n`);
for (const d of drifts) {
    if (d.kind === 'table-added') {
        console.log(`  + table: ${d.table} (in live DB, not in snapshot)`);
    } else if (d.kind === 'table-removed') {
        console.log(`  - table: ${d.table} (in snapshot, not in live DB)`);
    } else if (d.kind === 'column-added') {
        console.log(`  + ${d.table}.${d.column} (${d.live.type}${d.live.nullable ? ' NULL' : ' NOT NULL'}${d.live.default ? ` default ${d.live.default}` : ''})`);
    } else if (d.kind === 'column-removed') {
        console.log(`  - ${d.table}.${d.column} (was ${d.snapshot.type})`);
    } else if (d.kind === 'column-changed') {
        console.log(`  ~ ${d.table}.${d.column}: snapshot=${JSON.stringify(d.snapshot)} live=${JSON.stringify(d.live)}`);
    }
}

console.log(`\n[check:schema] Refresh: regenerate scripts/schema-snapshot.json from information_schema.columns and commit.\n`);

if (ALLOW_DRIFT) {
    console.log('[check:schema] --allow-drift passed; exiting 0.');
    process.exit(0);
}
process.exit(1);
